// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-02-23 14:54:22.198168 +0800 CST m=+0.071685116

package docs

import (
	"bytes"
	"encoding/json"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "用户中心",
        "title": "ums",
        "contact": {
            "name": "richard sun",
            "email": "cugriver@163.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "0.0.1"
    },
    "host": "localhost:13172",
    "basePath": "/",
    "paths": {
        "/v1/address": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "新增地址",
                "parameters": [
                    {
                        "type": "string",
                        "description": "语言",
                        "name": "x-language",
                        "in": "header"
                    },
                    {
                        "description": "CreateAddress",
                        "name": "{}",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Address"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpOk"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    }
                }
            }
        },
        "/v1/carts": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "查询购物车",
                "parameters": [
                    {
                        "type": "string",
                        "description": "语言",
                        "name": "x-language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpOk"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "添加购物车",
                "parameters": [
                    {
                        "type": "string",
                        "description": "语言",
                        "name": "x-language",
                        "in": "header"
                    },
                    {
                        "description": "CreateCart",
                        "name": "{}",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Cart"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpOk"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    }
                }
            }
        },
        "/v1/carts/{pathId}": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "summary": "更新购物车",
                "parameters": [
                    {
                        "type": "string",
                        "description": "语言",
                        "name": "x-language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpOk"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "summary": "删除购物车",
                "parameters": [
                    {
                        "type": "string",
                        "description": "语言",
                        "name": "x-language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpOk"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    }
                }
            }
        },
        "/v1/credit": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "新增卡片",
                "parameters": [
                    {
                        "type": "string",
                        "description": "语言",
                        "name": "x-language",
                        "in": "header"
                    },
                    {
                        "description": "CreateCreditCard",
                        "name": "{}",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.CreditCard"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpOk"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    }
                }
            }
        },
        "/v1/images": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "新增图片",
                "parameters": [
                    {
                        "type": "string",
                        "description": "语言",
                        "name": "x-language",
                        "in": "header"
                    },
                    {
                        "description": "CreateImage",
                        "name": "{}",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Image"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpOk"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    }
                }
            }
        },
        "/v1/tokens": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "获取令牌",
                "parameters": [
                    {
                        "type": "string",
                        "description": "语言",
                        "name": "x-language",
                        "in": "header"
                    },
                    {
                        "description": "LoginToken",
                        "name": "{}",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Token"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpOk"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    }
                }
            }
        },
        "/v1/users": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "语言",
                        "name": "x-language",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "时间戳",
                        "name": "timestamp",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "令牌",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "数字签名",
                        "name": "sign",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpOk"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "type": "string",
                        "description": "语言",
                        "name": "x-language",
                        "in": "header"
                    },
                    {
                        "description": "CreateUser",
                        "name": "{}",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Register"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpOk"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/route.httpError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.Address": {
            "type": "object",
            "properties": {
                "city": {
                    "description": "城市",
                    "type": "string"
                },
                "country": {
                    "description": "国家",
                    "type": "string"
                },
                "createTime": {
                    "type": "integer"
                },
                "deleteTime": {
                    "type": "integer"
                },
                "fullName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isDefault": {
                    "type": "boolean"
                },
                "line1": {
                    "description": "Line 1",
                    "type": "string"
                },
                "line2": {
                    "description": "Line 2",
                    "type": "string"
                },
                "phone": {
                    "description": "收货人电话",
                    "type": "string"
                },
                "province": {
                    "description": "省",
                    "type": "string"
                },
                "updateTime": {
                    "type": "integer"
                },
                "zipCode": {
                    "description": "邮编",
                    "type": "string"
                }
            }
        },
        "api.Cart": {
            "type": "object",
            "properties": {
                "colorId": {
                    "type": "string"
                },
                "colorName": {
                    "type": "object",
                    "$ref": "#/definitions/api.Languages"
                },
                "count": {
                    "type": "integer"
                },
                "createTime": {
                    "type": "integer"
                },
                "deleteTime": {
                    "type": "integer"
                },
                "frontImage": {
                    "type": "string"
                },
                "goodsId": {
                    "type": "string"
                },
                "goodsName": {
                    "type": "object",
                    "$ref": "#/definitions/api.Languages"
                },
                "goodsPrice": {
                    "type": "number"
                },
                "goodsStatus": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "sizeId": {
                    "type": "string"
                },
                "sizeValue": {
                    "type": "string"
                },
                "updateTime": {
                    "type": "integer"
                }
            }
        },
        "api.CreditCard": {
            "type": "object",
            "properties": {
                "bin": {
                    "type": "string"
                },
                "createTime": {
                    "type": "integer"
                },
                "cvv": {
                    "type": "string"
                },
                "deleteTime": {
                    "type": "integer"
                },
                "expire": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isDefault": {
                    "type": "boolean"
                },
                "number": {
                    "type": "string"
                },
                "updateTime": {
                    "type": "integer"
                }
            }
        },
        "api.Image": {
            "type": "object",
            "properties": {
                "createTime": {
                    "type": "integer"
                },
                "deleteTime": {
                    "type": "integer"
                },
                "direction": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "sequence": {
                    "type": "integer"
                },
                "updateTime": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "api.Languages": {
            "type": "object",
            "properties": {
                "chinese": {
                    "type": "string"
                },
                "english": {
                    "type": "string"
                }
            }
        },
        "api.Register": {
            "type": "object",
            "properties": {
                "gender": {
                    "description": "0 women 1 man",
                    "type": "integer"
                },
                "password": {
                    "description": "sha1(password)",
                    "type": "string"
                },
                "sign": {
                    "description": "签名",
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "username": {
                    "description": "email",
                    "type": "string"
                }
            }
        },
        "api.Token": {
            "type": "object",
            "properties": {
                "category": {
                    "description": "token 分类",
                    "type": "integer"
                },
                "username": {
                    "description": "email",
                    "type": "string"
                }
            }
        },
        "route.httpError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "route.httpOk": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{ Schemes: []string{"http","https"}}

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface {}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
