basePath: /
definitions:
  api.Image:
    properties:
      createTime:
        type: integer
      deleteTime:
        type: integer
      direction:
        type: integer
      id:
        type: string
      sequence:
        type: integer
      updateTime:
        type: integer
      url:
        type: string
    type: object
  api.Register:
    properties:
      gender:
        description: 0 women 1 man
        type: integer
      password:
        description: sha1(password)
        type: string
      timestamp:
        type: integer
      token:
        type: string
      username:
        description: email
        type: string
      verified:
        description: 邮件验证码
        type: string
    type: object
  api.Token:
    properties:
      category:
        description: token 分类
        type: integer
      username:
        description: email
        type: string
    type: object
  route.httpError:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  route.httpOk:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
host: localhost:13172
info:
  contact:
    email: cugriver@163.com
    name: richard sun
  description: 用户中心
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: ums
  version: 0.0.1
paths:
  /v1/images:
    post:
      parameters:
      - description: 语言
        in: header
        name: x-language
        type: string
      - description: CreateImage
        in: body
        name: '{}'
        required: true
        schema:
          $ref: '#/definitions/api.Image'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/route.httpOk'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/route.httpError'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/route.httpError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/route.httpError'
            type: object
      summary: 新增图片
  /v1/tokens:
    post:
      parameters:
      - description: 语言
        in: header
        name: x-language
        type: string
      - description: LoginToken
        in: body
        name: '{}'
        required: true
        schema:
          $ref: '#/definitions/api.Token'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/route.httpOk'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/route.httpError'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/route.httpError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/route.httpError'
            type: object
      summary: 获取用户登录令牌 有效器 1800s
  /v1/users:
    get:
      parameters:
      - description: 语言
        in: header
        name: x-language
        type: string
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      - description: 时间戳
        in: query
        name: timestamp
        required: true
        type: integer
      - description: 令牌
        in: query
        name: token
        required: true
        type: string
      - description: 数字签名
        in: query
        name: sign
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/route.httpOk'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/route.httpError'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/route.httpError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/route.httpError'
            type: object
      summary: 用户登录
    post:
      parameters:
      - description: 语言
        in: header
        name: x-language
        type: string
      - description: CreateUser
        in: body
        name: '{}'
        required: true
        schema:
          $ref: '#/definitions/api.Register'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/route.httpOk'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/route.httpError'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/route.httpError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/route.httpError'
            type: object
      summary: 用户注册
swagger: "2.0"
