basePath: /
definitions:
  route.HttpError:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  route.HttpOk:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  route.RequestBrand:
    properties:
      brandNameCn:
        type: string
      brandNameEn:
        type: string
      brandStatus:
        type: integer
    type: object
  route.RequestCategory:
    properties:
      categoryName:
        type: string
      categoryStatus:
        type: integer
      childCategories:
        items:
          type: string
        type: array
      parentCategories:
        items:
          type: string
        type: array
    type: object
  route.RequestSize:
    properties:
      sizeNameCn:
        type: string
      sizeNameEn:
        type: string
      sizeStatus:
        type: integer
    type: object
  route.RequestStyle:
    properties:
      sizeNameCn:
        type: string
      sizeNameEn:
        type: string
      sizeStatus:
        type: integer
      styleDescriptionCn:
        type: string
      styleDescriptionEn:
        type: string
    type: object
  route.ResponseVersion:
    properties:
      info:
        type: string
    type: object
host: localhost:13147
info:
  contact:
    email: cugriver@163.com
    name: richard sun
  description: 商品中心
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: mms
  version: 0.0.1
paths:
  /v1/brands:
    get:
      parameters:
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页条数
        in: query
        name: perPage
        type: integer
      - description: 状态
        in: query
        name: status
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/route.HttpOk'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
      summary: 查询品牌列表
    post:
      parameters:
      - description: CreateBrand
        in: body
        name: '{}'
        required: true
        schema:
          $ref: '#/definitions/route.RequestBrand'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/route.HttpOk'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
      summary: 创建品牌
  /v1/brands/{pathId}:
    delete:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/route.HttpOk'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
      summary: 删除品牌
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/route.HttpOk'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
      summary: 查询品牌
    put:
      parameters:
      - description: UpdateBrand
        in: body
        name: '{}'
        required: true
        schema:
          $ref: '#/definitions/route.RequestBrand'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/route.HttpOk'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
      summary: 更新品牌
  /v1/categories:
    post:
      parameters:
      - description: CreateCategory
        in: body
        name: '{}'
        required: true
        schema:
          $ref: '#/definitions/route.RequestCategory'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/route.HttpOk'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
      summary: 创建分类
  /v1/merchandises:
    get:
      parameters:
      - description: QueryMerchandises
        in: body
        name: '{}'
        required: true
        schema:
          $ref: '#/definitions/route.RequestCategory'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/route.HttpOk'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
      summary: 查询商品列表
    post:
      parameters:
      - description: CreateMerchandise
        in: body
        name: '{}'
        required: true
        schema:
          $ref: '#/definitions/route.RequestCategory'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/route.HttpOk'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
      summary: 创建商品
  /v1/merchandises/{goodsId}:
    delete:
      parameters:
      - description: DeleteMerchandise
        in: body
        name: '{}'
        required: true
        schema:
          $ref: '#/definitions/route.RequestCategory'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/route.HttpOk'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
      summary: 删除商品
    get:
      parameters:
      - description: QueryMerchandise
        in: body
        name: '{}'
        required: true
        schema:
          $ref: '#/definitions/route.RequestCategory'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/route.HttpOk'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
      summary: 查询商品
    put:
      parameters:
      - description: UpdateMerchandise
        in: body
        name: '{}'
        required: true
        schema:
          $ref: '#/definitions/route.RequestCategory'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/route.HttpOk'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
      summary: 更新商品
  /v1/services/version:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/route.ResponseVersion'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
      summary: 显示当前服务的版本和代码版本号
  /v1/sizes:
    get:
      parameters:
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页条数
        in: query
        name: perPage
        type: integer
      - description: 状态
        in: query
        name: status
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/route.HttpOk'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
      summary: 查询尺码列表
    post:
      parameters:
      - description: CreateSize
        in: body
        name: '{}'
        required: true
        schema:
          $ref: '#/definitions/route.RequestSize'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/route.HttpOk'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
      summary: 创建尺码
  /v1/sizes/{pathId}:
    delete:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/route.HttpOk'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
      summary: 删除尺码
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/route.HttpOk'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
      summary: 查询尺码
    put:
      parameters:
      - description: UpdateSize
        in: body
        name: '{}'
        required: true
        schema:
          $ref: '#/definitions/route.RequestSize'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/route.HttpOk'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
      summary: 更新品牌
  /v1/styles:
    get:
      parameters:
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页条数
        in: query
        name: perPage
        type: integer
      - description: 状态
        in: query
        name: status
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/route.HttpOk'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
      summary: 查询款式列表
    post:
      parameters:
      - description: CreateStyle
        in: body
        name: '{}'
        required: true
        schema:
          $ref: '#/definitions/route.RequestStyle'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/route.HttpOk'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
      summary: 创建款式
  /v1/styles/{pathId}:
    delete:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/route.HttpOk'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
      summary: 删除款式
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/route.HttpOk'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
      summary: 查询款式
    put:
      parameters:
      - description: UpdateStyle
        in: body
        name: '{}'
        required: true
        schema:
          $ref: '#/definitions/route.RequestStyle'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/route.HttpOk'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/route.HttpError'
            type: object
      summary: 更新款式
swagger: "2.0"
